# Generated by Django 4.2.17 on 2025-01-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffeechat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coffeechat",
            name="is_public",
        ),
        migrations.AddField(
            model_name="coffeechat",
            name="profile_status",
            field=models.CharField(
                choices=[("F2F", "대면"), ("ONLINE", "비대면"), ("OFF", "오프")],
                default="F2F",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="coffeechatrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING", "수락대기중"),
                    ("ONGOING", "진행중"),
                    ("ACCEPTED", "수락"),
                    ("LIMITED", "최대요청횟수초과"),
                    ("PRIVATE", "비공개"),
                    ("REJECTED", "거절"),
                    ("COMPLETED", "완료"),
                ],
                default="WAITING",
                max_length=10,
            ),
        ),
    ]
