# Generated by Django 5.0.6 on 2025-01-05 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='coffeeChatRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='coffeechat.coffeechat'),
        ),
    ]
