# Generated by Django 4.2.17 on 2025-01-05 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeechat', '0002_coffeechat_accepted_at_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='coffeeChatRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='coffeechat.coffeechat'),
        ),
    ]
