# Generated by Django 4.2.17 on 2025-01-05 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeechat', '0002_alter_memo_coffeechatrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='coffeeChatRequest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memo', to='coffeechat.coffeechat'),
        ),
    ]
