# Generated by Django 5.0.6 on 2025-01-05 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memo',
        ),
    ]
