# Generated by Django 4.2.17 on 2025-01-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Memo",
        ),
    ]
